import { create } from 'zustand';

// appStore — Estado extendido de SISO-APP
// Contiene los useState del monolito no cubiertos por otros stores

export const useAppStore = create((set) => ({
  auditLog: null,
  data: null,
  isGenerating: false,
  isGeneratingRestr: false,
  isGeneratingReco: false,
  saveStatus: "",
  _hcDirty: false,
  _exitHcConfirm: null,
  patientSuggestions: [],
  historyNotification: null,
  showRestriccionesPanel: false,
  showHistoryModal: false,
  ripsModalData: null,
  backupModalData: null,
  hcChoiceAgenda: null,
  historyRecords: [],
  genPatSearch: null,
  examSearch: null,
  examList: null,
  showExamSuggs: false,
  diagExamen: "",
  justExamen: "",
  printPreview: null,
  selectedCompanyReport: "",
  reporteActiveTab: null,
  certSelected: null,
  reportStartDate: "",
  reportEndDate: "",
  reportAIResult: null,
  isGeneratingReport: false,
  showExportTable: false,
  precioPorPaciente: "",
  showDianPanel: false,
  dianProvider: null,
  dianApiKey: null,
  billData: null,
  savedBillsList: [],
  portafolioItems: null,
  portafolioForm: null,
  portafolioEditId: null,
  cotizaciones: null,
  cotizacionForm: null,
  cotizacionView: "list",
  cotizacionSelId: null,
  cajaMovimientos: null,
  cajaForm: null,
  cajaTab: "hoy",
  cajaFiltroPeriodo: "hoy",
  cajaFiltroDesde: "",
  cajaFiltroHasta: "",
  contabTab: "resumen",
  contabPeriodo: "mes",
  asistenciaFecha: null,
  evolucionForm: null,
  showEvolucionModal: false,
  selectedPackage: null,
  packageChecklist: {},
  showPackages: false,
  newComp: null,
  ipsPerfilForm: null,
  verificationCode: "",
  verificationFound: null,
  activeUserMgmtTab: "list",
  pendingActivationPlan: null,
  sbCloudData: null,
  sbLoading: false,
  newUserForm: null,
  userEditId: null,
  editForm: {},
  propForm: null,
  selSvc: "",
  propModulo: null,
  mensajes: null,
  showMensajePanel: false,
  showConsentModal: null,
  twoFAStep: null,
  twoFAToken: "",
  twoFAError: "",
  habeasRequests: null,
  showHabeasModal: false,
  habeasForm: null,
  showPortalPublico: false,
  arlTab: "at",
  svePrograma: "DME",
  sveFiltroEmpresa: "",
  sveAIAnalisis: null,
  sveAICargando: false,
  sveAIFiltroEmpresa: "",
  arlForm: {},
  arlGuardados: null,
  showNotifModal: false,
  notifData: {},
  portalCodigo: "",
  portalPaciente: null,
  portalMultiple: null,
  epiEmpresa: "todas",
  epiPeriodo: "anio",
  epiTab: "resumen",
  teleconsultas: null,
  teleForm: null,
  teleSalaActiva: null,
  teleTab: null,
  mensajeRespuesta: null,
  agendados: null,
  showAgenda: false,
  agendaForm: null,
  agendaSuggs: [],
  agendaTab: null,
  showComposeMensaje: false,
  composeMensaje: null,
  inactivityWarning: false,
  inactivityCountdown: 0,
  companiesTab: "lista",
  editingCompany: null,
  cajaMedicoPeriodo: "mes",
  porcentajeMedico: null,
  medicoTurnoActivo: null,
  orgsList: null,
  activeOrgId: null,
  superAdminTab: "orgs",
  newOrgForm: null,
  portalEmpresaCodigo: "",
  portalEmpresaEncontrada: null,
  portalEmpresaPacientes: [],
  portalEmpresaTab: "trabajadores",
  portalEmpresaBuscando: false,
  portalEmpresaFiltroDoc: null,
  portalActivadoInfo: null,
  portalEmpresaAdmin: null,
  portalAdminTab: "medicos",
  portalAdminLoginUser: "",
  portalAdminLoginPass: "",
  nuevoMedicoEmpForm: null,
  sedeForm: null,
  ipsCredForm: null,
  ipsEditingEmpId: null,

  // Setters genéricos
  setAuditLog: (v) => set((s) => ({ auditLog: typeof v === 'function' ? v(s.auditLog) : v })),
  setData: (v) => set((s) => ({ data: typeof v === 'function' ? v(s.data) : v })),
  setIsGenerating: (v) => set((s) => ({ isGenerating: typeof v === 'function' ? v(s.isGenerating) : v })),
  setIsGeneratingRestr: (v) => set((s) => ({ isGeneratingRestr: typeof v === 'function' ? v(s.isGeneratingRestr) : v })),
  setIsGeneratingReco: (v) => set((s) => ({ isGeneratingReco: typeof v === 'function' ? v(s.isGeneratingReco) : v })),
  setSaveStatus: (v) => set((s) => ({ saveStatus: typeof v === 'function' ? v(s.saveStatus) : v })),
  _setHcDirty: (v) => set((s) => ({ _hcDirty: typeof v === 'function' ? v(s._hcDirty) : v })),
  _setExitHcConfirm: (v) => set((s) => ({ _exitHcConfirm: typeof v === 'function' ? v(s._exitHcConfirm) : v })),
  setPatientSuggestions: (v) => set((s) => ({ patientSuggestions: typeof v === 'function' ? v(s.patientSuggestions) : v })),
  setHistoryNotification: (v) => set((s) => ({ historyNotification: typeof v === 'function' ? v(s.historyNotification) : v })),
  setShowRestriccionesPanel: (v) => set((s) => ({ showRestriccionesPanel: typeof v === 'function' ? v(s.showRestriccionesPanel) : v })),
  setShowHistoryModal: (v) => set((s) => ({ showHistoryModal: typeof v === 'function' ? v(s.showHistoryModal) : v })),
  setRipsModalData: (v) => set((s) => ({ ripsModalData: typeof v === 'function' ? v(s.ripsModalData) : v })),
  setBackupModalData: (v) => set((s) => ({ backupModalData: typeof v === 'function' ? v(s.backupModalData) : v })),
  setHcChoiceAgenda: (v) => set((s) => ({ hcChoiceAgenda: typeof v === 'function' ? v(s.hcChoiceAgenda) : v })),
  setHistoryRecords: (v) => set((s) => ({ historyRecords: typeof v === 'function' ? v(s.historyRecords) : v })),
  setGenPatSearch: (v) => set((s) => ({ genPatSearch: typeof v === 'function' ? v(s.genPatSearch) : v })),
  setExamSearch: (v) => set((s) => ({ examSearch: typeof v === 'function' ? v(s.examSearch) : v })),
  setExamList: (v) => set((s) => ({ examList: typeof v === 'function' ? v(s.examList) : v })),
  setShowExamSuggs: (v) => set((s) => ({ showExamSuggs: typeof v === 'function' ? v(s.showExamSuggs) : v })),
  setDiagExamen: (v) => set((s) => ({ diagExamen: typeof v === 'function' ? v(s.diagExamen) : v })),
  setJustExamen: (v) => set((s) => ({ justExamen: typeof v === 'function' ? v(s.justExamen) : v })),
  setPrintPreview: (v) => set((s) => ({ printPreview: typeof v === 'function' ? v(s.printPreview) : v })),
  setSelectedCompanyReport: (v) => set((s) => ({ selectedCompanyReport: typeof v === 'function' ? v(s.selectedCompanyReport) : v })),
  setReporteActiveTab: (v) => set((s) => ({ reporteActiveTab: typeof v === 'function' ? v(s.reporteActiveTab) : v })),
  setCertSelected: (v) => set((s) => ({ certSelected: typeof v === 'function' ? v(s.certSelected) : v })),
  setReportStartDate: (v) => set((s) => ({ reportStartDate: typeof v === 'function' ? v(s.reportStartDate) : v })),
  setReportEndDate: (v) => set((s) => ({ reportEndDate: typeof v === 'function' ? v(s.reportEndDate) : v })),
  setReportAIResult: (v) => set((s) => ({ reportAIResult: typeof v === 'function' ? v(s.reportAIResult) : v })),
  setIsGeneratingReport: (v) => set((s) => ({ isGeneratingReport: typeof v === 'function' ? v(s.isGeneratingReport) : v })),
  setShowExportTable: (v) => set((s) => ({ showExportTable: typeof v === 'function' ? v(s.showExportTable) : v })),
  setPrecioPorPaciente: (v) => set((s) => ({ precioPorPaciente: typeof v === 'function' ? v(s.precioPorPaciente) : v })),
  setShowDianPanel: (v) => set((s) => ({ showDianPanel: typeof v === 'function' ? v(s.showDianPanel) : v })),
  setDianProvider: (v) => set((s) => ({ dianProvider: typeof v === 'function' ? v(s.dianProvider) : v })),
  setDianApiKey: (v) => set((s) => ({ dianApiKey: typeof v === 'function' ? v(s.dianApiKey) : v })),
  setBillData: (v) => set((s) => ({ billData: typeof v === 'function' ? v(s.billData) : v })),
  setSavedBillsList: (v) => set((s) => ({ savedBillsList: typeof v === 'function' ? v(s.savedBillsList) : v })),
  setPortafolioItems: (v) => set((s) => ({ portafolioItems: typeof v === 'function' ? v(s.portafolioItems) : v })),
  setPortafolioForm: (v) => set((s) => ({ portafolioForm: typeof v === 'function' ? v(s.portafolioForm) : v })),
  setPortafolioEditId: (v) => set((s) => ({ portafolioEditId: typeof v === 'function' ? v(s.portafolioEditId) : v })),
  setCotizaciones: (v) => set((s) => ({ cotizaciones: typeof v === 'function' ? v(s.cotizaciones) : v })),
  setCotizacionForm: (v) => set((s) => ({ cotizacionForm: typeof v === 'function' ? v(s.cotizacionForm) : v })),
  setCotizacionView: (v) => set((s) => ({ cotizacionView: typeof v === 'function' ? v(s.cotizacionView) : v })),
  setCotizacionSelId: (v) => set((s) => ({ cotizacionSelId: typeof v === 'function' ? v(s.cotizacionSelId) : v })),
  setCajaMovimientos: (v) => set((s) => ({ cajaMovimientos: typeof v === 'function' ? v(s.cajaMovimientos) : v })),
  setCajaForm: (v) => set((s) => ({ cajaForm: typeof v === 'function' ? v(s.cajaForm) : v })),
  setCajaTab: (v) => set((s) => ({ cajaTab: typeof v === 'function' ? v(s.cajaTab) : v })),
  setCajaFiltroPeriodo: (v) => set((s) => ({ cajaFiltroPeriodo: typeof v === 'function' ? v(s.cajaFiltroPeriodo) : v })),
  setCajaFiltroDesde: (v) => set((s) => ({ cajaFiltroDesde: typeof v === 'function' ? v(s.cajaFiltroDesde) : v })),
  setCajaFiltroHasta: (v) => set((s) => ({ cajaFiltroHasta: typeof v === 'function' ? v(s.cajaFiltroHasta) : v })),
  setContabTab: (v) => set((s) => ({ contabTab: typeof v === 'function' ? v(s.contabTab) : v })),
  setContabPeriodo: (v) => set((s) => ({ contabPeriodo: typeof v === 'function' ? v(s.contabPeriodo) : v })),
  setAsistenciaFecha: (v) => set((s) => ({ asistenciaFecha: typeof v === 'function' ? v(s.asistenciaFecha) : v })),
  setEvolucionForm: (v) => set((s) => ({ evolucionForm: typeof v === 'function' ? v(s.evolucionForm) : v })),
  setShowEvolucionModal: (v) => set((s) => ({ showEvolucionModal: typeof v === 'function' ? v(s.showEvolucionModal) : v })),
  setSelectedPackage: (v) => set((s) => ({ selectedPackage: typeof v === 'function' ? v(s.selectedPackage) : v })),
  setPackageChecklist: (v) => set((s) => ({ packageChecklist: typeof v === 'function' ? v(s.packageChecklist) : v })),
  setShowPackages: (v) => set((s) => ({ showPackages: typeof v === 'function' ? v(s.showPackages) : v })),
  setNewComp: (v) => set((s) => ({ newComp: typeof v === 'function' ? v(s.newComp) : v })),
  setIpsPerfilForm: (v) => set((s) => ({ ipsPerfilForm: typeof v === 'function' ? v(s.ipsPerfilForm) : v })),
  setVerificationCode: (v) => set((s) => ({ verificationCode: typeof v === 'function' ? v(s.verificationCode) : v })),
  setVerificationFound: (v) => set((s) => ({ verificationFound: typeof v === 'function' ? v(s.verificationFound) : v })),
  setActiveUserMgmtTab: (v) => set((s) => ({ activeUserMgmtTab: typeof v === 'function' ? v(s.activeUserMgmtTab) : v })),
  setPendingActivationPlan: (v) => set((s) => ({ pendingActivationPlan: typeof v === 'function' ? v(s.pendingActivationPlan) : v })),
  setSbCloudData: (v) => set((s) => ({ sbCloudData: typeof v === 'function' ? v(s.sbCloudData) : v })),
  setSbLoading: (v) => set((s) => ({ sbLoading: typeof v === 'function' ? v(s.sbLoading) : v })),
  setNewUserForm: (v) => set((s) => ({ newUserForm: typeof v === 'function' ? v(s.newUserForm) : v })),
  setUserEditId: (v) => set((s) => ({ userEditId: typeof v === 'function' ? v(s.userEditId) : v })),
  setEditForm: (v) => set((s) => ({ editForm: typeof v === 'function' ? v(s.editForm) : v })),
  setPropForm: (v) => set((s) => ({ propForm: typeof v === 'function' ? v(s.propForm) : v })),
  setSelSvc: (v) => set((s) => ({ selSvc: typeof v === 'function' ? v(s.selSvc) : v })),
  setPropModulo: (v) => set((s) => ({ propModulo: typeof v === 'function' ? v(s.propModulo) : v })),
  setMensajes: (v) => set((s) => ({ mensajes: typeof v === 'function' ? v(s.mensajes) : v })),
  setShowMensajePanel: (v) => set((s) => ({ showMensajePanel: typeof v === 'function' ? v(s.showMensajePanel) : v })),
  setShowConsentModal: (v) => set((s) => ({ showConsentModal: typeof v === 'function' ? v(s.showConsentModal) : v })),
  setTwoFAStep: (v) => set((s) => ({ twoFAStep: typeof v === 'function' ? v(s.twoFAStep) : v })),
  setTwoFAToken: (v) => set((s) => ({ twoFAToken: typeof v === 'function' ? v(s.twoFAToken) : v })),
  setTwoFAError: (v) => set((s) => ({ twoFAError: typeof v === 'function' ? v(s.twoFAError) : v })),
  setHabeasRequests: (v) => set((s) => ({ habeasRequests: typeof v === 'function' ? v(s.habeasRequests) : v })),
  setShowHabeasModal: (v) => set((s) => ({ showHabeasModal: typeof v === 'function' ? v(s.showHabeasModal) : v })),
  setHabeasForm: (v) => set((s) => ({ habeasForm: typeof v === 'function' ? v(s.habeasForm) : v })),
  setShowPortalPublico: (v) => set((s) => ({ showPortalPublico: typeof v === 'function' ? v(s.showPortalPublico) : v })),
  setArlTab: (v) => set((s) => ({ arlTab: typeof v === 'function' ? v(s.arlTab) : v })),
  setSvePrograma: (v) => set((s) => ({ svePrograma: typeof v === 'function' ? v(s.svePrograma) : v })),
  setSveFiltroEmpresa: (v) => set((s) => ({ sveFiltroEmpresa: typeof v === 'function' ? v(s.sveFiltroEmpresa) : v })),
  setSveAIAnalisis: (v) => set((s) => ({ sveAIAnalisis: typeof v === 'function' ? v(s.sveAIAnalisis) : v })),
  setSveAIAnalisisCargando: (v) => set((s) => ({ sveAICargando: typeof v === 'function' ? v(s.sveAICargando) : v })),
  setSveAIFiltroEmpresa: (v) => set((s) => ({ sveAIFiltroEmpresa: typeof v === 'function' ? v(s.sveAIFiltroEmpresa) : v })),
  setArlForm: (v) => set((s) => ({ arlForm: typeof v === 'function' ? v(s.arlForm) : v })),
  setArlGuardados: (v) => set((s) => ({ arlGuardados: typeof v === 'function' ? v(s.arlGuardados) : v })),
  setShowNotifModal: (v) => set((s) => ({ showNotifModal: typeof v === 'function' ? v(s.showNotifModal) : v })),
  setNotifData: (v) => set((s) => ({ notifData: typeof v === 'function' ? v(s.notifData) : v })),
  setPortalCodigo: (v) => set((s) => ({ portalCodigo: typeof v === 'function' ? v(s.portalCodigo) : v })),
  setPortalPaciente: (v) => set((s) => ({ portalPaciente: typeof v === 'function' ? v(s.portalPaciente) : v })),
  setPortalMultiple: (v) => set((s) => ({ portalMultiple: typeof v === 'function' ? v(s.portalMultiple) : v })),
  setEpiEmpresa: (v) => set((s) => ({ epiEmpresa: typeof v === 'function' ? v(s.epiEmpresa) : v })),
  setEpiPeriodo: (v) => set((s) => ({ epiPeriodo: typeof v === 'function' ? v(s.epiPeriodo) : v })),
  setEpiTab: (v) => set((s) => ({ epiTab: typeof v === 'function' ? v(s.epiTab) : v })),
  setTeleconsultas: (v) => set((s) => ({ teleconsultas: typeof v === 'function' ? v(s.teleconsultas) : v })),
  setTeleForm: (v) => set((s) => ({ teleForm: typeof v === 'function' ? v(s.teleForm) : v })),
  setTeleSalaActiva: (v) => set((s) => ({ teleSalaActiva: typeof v === 'function' ? v(s.teleSalaActiva) : v })),
  setTeleTab: (v) => set((s) => ({ teleTab: typeof v === 'function' ? v(s.teleTab) : v })),
  setMensajeRespuesta: (v) => set((s) => ({ mensajeRespuesta: typeof v === 'function' ? v(s.mensajeRespuesta) : v })),
  setAgendados: (v) => set((s) => ({ agendados: typeof v === 'function' ? v(s.agendados) : v })),
  setShowAgenda: (v) => set((s) => ({ showAgenda: typeof v === 'function' ? v(s.showAgenda) : v })),
  setAgendaForm: (v) => set((s) => ({ agendaForm: typeof v === 'function' ? v(s.agendaForm) : v })),
  setAgendaSuggs: (v) => set((s) => ({ agendaSuggs: typeof v === 'function' ? v(s.agendaSuggs) : v })),
  setAgendaTab: (v) => set((s) => ({ agendaTab: typeof v === 'function' ? v(s.agendaTab) : v })),
  setShowComposeMensaje: (v) => set((s) => ({ showComposeMensaje: typeof v === 'function' ? v(s.showComposeMensaje) : v })),
  setComposeMensaje: (v) => set((s) => ({ composeMensaje: typeof v === 'function' ? v(s.composeMensaje) : v })),
  setInactivityWarning: (v) => set((s) => ({ inactivityWarning: typeof v === 'function' ? v(s.inactivityWarning) : v })),
  setInactivityCountdown: (v) => set((s) => ({ inactivityCountdown: typeof v === 'function' ? v(s.inactivityCountdown) : v })),
  setCompaniesTab: (v) => set((s) => ({ companiesTab: typeof v === 'function' ? v(s.companiesTab) : v })),
  setEditingCompany: (v) => set((s) => ({ editingCompany: typeof v === 'function' ? v(s.editingCompany) : v })),
  setCajaMedicoPeriodo: (v) => set((s) => ({ cajaMedicoPeriodo: typeof v === 'function' ? v(s.cajaMedicoPeriodo) : v })),
  setPorcentajeMedico: (v) => set((s) => ({ porcentajeMedico: typeof v === 'function' ? v(s.porcentajeMedico) : v })),
  setMedicoTurnoActivo: (v) => set((s) => ({ medicoTurnoActivo: typeof v === 'function' ? v(s.medicoTurnoActivo) : v })),
  setOrgsList: (v) => set((s) => ({ orgsList: typeof v === 'function' ? v(s.orgsList) : v })),
  setActiveOrgId: (v) => set((s) => ({ activeOrgId: typeof v === 'function' ? v(s.activeOrgId) : v })),
  setSuperAdminTab: (v) => set((s) => ({ superAdminTab: typeof v === 'function' ? v(s.superAdminTab) : v })),
  setNewOrgForm: (v) => set((s) => ({ newOrgForm: typeof v === 'function' ? v(s.newOrgForm) : v })),
  setPortalEmpresaCodigo: (v) => set((s) => ({ portalEmpresaCodigo: typeof v === 'function' ? v(s.portalEmpresaCodigo) : v })),
  setPortalEmpresaEncontrada: (v) => set((s) => ({ portalEmpresaEncontrada: typeof v === 'function' ? v(s.portalEmpresaEncontrada) : v })),
  setPortalEmpresaPacientes: (v) => set((s) => ({ portalEmpresaPacientes: typeof v === 'function' ? v(s.portalEmpresaPacientes) : v })),
  setPortalEmpresaTab: (v) => set((s) => ({ portalEmpresaTab: typeof v === 'function' ? v(s.portalEmpresaTab) : v })),
  setPortalEmpresaBuscando: (v) => set((s) => ({ portalEmpresaBuscando: typeof v === 'function' ? v(s.portalEmpresaBuscando) : v })),
  setPortalEmpresaFiltroDoc: (v) => set((s) => ({ portalEmpresaFiltroDoc: typeof v === 'function' ? v(s.portalEmpresaFiltroDoc) : v })),
  setPortalActivadoInfo: (v) => set((s) => ({ portalActivadoInfo: typeof v === 'function' ? v(s.portalActivadoInfo) : v })),
  setPortalEmpresaAdmin: (v) => set((s) => ({ portalEmpresaAdmin: typeof v === 'function' ? v(s.portalEmpresaAdmin) : v })),
  setPortalAdminTab: (v) => set((s) => ({ portalAdminTab: typeof v === 'function' ? v(s.portalAdminTab) : v })),
  setPortalAdminLoginUser: (v) => set((s) => ({ portalAdminLoginUser: typeof v === 'function' ? v(s.portalAdminLoginUser) : v })),
  setPortalAdminLoginPass: (v) => set((s) => ({ portalAdminLoginPass: typeof v === 'function' ? v(s.portalAdminLoginPass) : v })),
  setNuevoMedicoEmpForm: (v) => set((s) => ({ nuevoMedicoEmpForm: typeof v === 'function' ? v(s.nuevoMedicoEmpForm) : v })),
  setSedeForm: (v) => set((s) => ({ sedeForm: typeof v === 'function' ? v(s.sedeForm) : v })),
  setIpsCredForm: (v) => set((s) => ({ ipsCredForm: typeof v === 'function' ? v(s.ipsCredForm) : v })),
  setIpsEditingEmpId: (v) => set((s) => ({ ipsEditingEmpId: typeof v === 'function' ? v(s.ipsEditingEmpId) : v })),
}));
